volumes:
  data:
  tool_cache:
  dind-storage:
  mcp_cache:

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:1.0.15
    command: run --path /data --host 0.0.0.0 --port 8200
    environment:
      CHROMA_SERVER_HTTP_PORT: "8200"
      CHROMA_SERVER_GRPC_PORT: "8230"
      CHROMA_DB_IMPL: "duckdb"
      CHROMA_TELEMETRY: "FALSE"
    volumes:
      - data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8200/api/v1/heartbeat" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  dind:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    volumes:
      - dind-storage:/var/lib/docker

  unix_command_builder:
    image: docker:cli
    depends_on:
      - dind
    volumes:
      - .:/src:ro
    environment:
      DOCKER_HOST: "tcp://dind:2375"
    entrypoint: [ "sh", "-c", "sleep 20 && cd /src && (docker volume create mcp_session || true) && docker build -t shyhurricane_unix_command:latest src/docker/unix_command && docker system prune -f" ]

  mcp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dind
      - unix_command_builder
      - chroma
    environment:
      DOCKER_HOST: "tcp://dind:2375"
      CHROMA: "chroma:8200"
      TOOL_CACHE: "/tool_cache"
      # no model seems to support this yet
      DISABLE_ELICITATION: "True"
      OLLAMA_MODEL: "${OLLAMA_MODEL:-qwen2.5:7b-instruct}"
      OLLAMA_URL: "${OLLAMA_URL:-http://127.0.0.1:11434}"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      GEMINI_MODEL: "${GEMINI_MODEL}"
      OPENAI_MODEL: "${OPENAI_MODEL}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      PYTORCH_ENABLE_MPS_FALLBACK: "1"
      ANONYMIZED_TELEMETRY: "False"
      HAYSTACK_TELEMETRY_ENABLED: "False"
      HAYSTACK_TELEMETRY_DISABLED: "1"
      TRANSFORMERS_NO_ADVISORY_WARNINGS: "1"
      HF_HUB_DISABLE_PROGRESS_BARS: "1"
      OMP_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
    shm_size: "2g"
    ports:
      - "8000:8000"
    volumes:
      - "data:/data"
      - "tool_cache:/tool_cache"
      - "mcp_cache:/home/runner/.cache"
